<?php

namespace EscuelaBundle\Repository;

/**
 * t_alumnosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class t_alumnosRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAlumno($alumno){
		$query = $this->createQueryBuilder('a')
        ->where('a.id = :alumno')
        ->orWhere('a.nombre = :alumno')
        ->setParameter(':alumno',$alumno)
        ->getQuery();
		return $query->getResult();
	}
}
