<?php

namespace EscuelaBundle\Repository;

/**
 * t_calificacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class t_calificacionesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCalificacion($alumno,$materia){
		$query = $this->createQueryBuilder('c')
        ->where('c.alumnos = :alumno')
        ->andWhere('c.materias = :materias')
        ->setParameter(':alumno',$alumno)
        ->setParameter(':materias',$materia)
        ->getQuery();
		return $query->getResult();
	}
}
