<?php

namespace EscuelaBundle\Repository;

/**
 * t_materiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class t_materiasRepository extends \Doctrine\ORM\EntityRepository
{
		public function findMateria($materia){
			$query = $this->createQueryBuilder('m')
	        ->where('m.id = :materia')
	        ->orWhere('m.nombre = :materia')
	        ->setParameter(':materia',$materia)
	        ->setParameter('materia',$materia)
	        ->getQuery()
	        ->getResult();
			return $query;
		}
}
